server:
  port: 8090

#?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: happyyzf@123
    url: jdbc:mysql://localhost:3306/webchat?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#??MyBits???????
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity


